name: Static Analysis

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, xml
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --no-interaction --no-progress

      - name: Install PHPStan
        run: composer bin phpstan update --no-interaction --no-progress

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress

  psalm:
    name: Psalm
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, dom, simplexml, xml
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --no-interaction --no-progress

      - name: Install Psalm
        run: composer bin psalm update --no-interaction --no-progress

      - name: Execute PHPStan
        run: vendor/bin/psalm --output-format=github
